# -*- coding: utf-8 -*-
"""shapeCalcs.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qyk7M2h_hEjyLZ46KCYr98WSnsCO1ukm
"""

#Louise Capener

#Define the function to be used in a while loop
def menu():
    print("[1] Find an Angle")
    print("[2] Find the Hypotenuse")
    print("[3] Find the Area")
    print("[q] Exit")



menu()
#Prompt the user to input their choice
#Input has to be string to enable option "q" to work
choice = input("Enter your choice, then hit [Enter]")

#******************************************************************************************************************************

while choice != "q":


    if choice == "1":
        #Commence choice 1
        #Mini-program 1

        #Cast KB input into integers
        #Prompt the user to enter a whole number, not a float or a string
        angle1 = int(input("Please enter the first angle as a whole number:"))
        angle2 = int(input("Thankyou! Now, please enter the second angle:"))

        #Calculate the sum of both angles to find the missing angle
        totalinT = 180
        angle3 = totalinT - (angle1 + angle2)
        print("The missing angle is:", angle3)

        #Line breaks have been added to enhance presentation
        print("Angle 1 =", angle1, u"\N{DEGREE SIGN}"'\n')
        print("Angle 2 =", angle2, u"\N{DEGREE SIGN}"'\n')
        print("Missing angle:", angle3, u"\N{DEGREE SIGN}"'\n')

#******************************************************************************************************************************

    elif choice == "2":
        #Commence choice 2
        #Mini-program 2

        print("Hello there, to calculate the hypotenuse of this right-angle triangle, I'm going to need your help.")
        l1 = int(input("Please enter the first length as a whole number:\n"))
        l2 = int(input("That's great! Please enter the second length:"))

        #Calculate the hypotenuse by taking a square root of the sum of squares
        l1sq = l1 ** 2
        l2sq = l2 ** 2
        hyp = (l1sq + l2sq) ** 0.5

        print("Length 1 =", l1, "cm" '\n')
        print("Length 2 =", l2, "cm" '\n')
        print("Length of hypotenuse =", hyp, "cm" '\n')
        print("Let's round that up!")
        #Round up the result to 2 decimal places
        print(round(hyp, 2),"cm")

#******************************************************************************************************************************

    elif choice == "3":
        #Commence choice 2
        #Mini-program 3

        print("Hello there, to calculate the area of this triangle, I'm going to need your help")
        le1 = int(input("Please enter the first length of the triangle as a whole number:"))
        le2 = int(input("Please enter the second length of the triangle:"))
        le3 = int(input("Finally, please enter the third length:"))


        #Calculate the area of the triangle using Heron's formula
        #Step 1: Calculate the semi-permiter by finding the sum of all 3 lengths and dividing by 2
        sp = (le1 + le2 + le3)/2

        #Step 2: Calculate area by individually multiplying the semi-perimeter by itself MINUS each length
        #New variable product represents the sum of the following calculation
        product = sp*(sp - le1)*(sp - le2)*(sp - le3)

        #Step 3: Calculate the square root of the product (of sp * sp - length) to find the area
        area = product ** 0.5


        print("Length 1 =", le1, "cm" '\n')
        print("Length 2 =", le2, "cm" '\n')
        print("Length 3 =", le3, "cm" '\n')
        print("And finally... The area of this triangle is:", area, "cm²")
        print("Let's round that up!")
        #Round up the result to 2 decimal places
        print(round(area, 2),"cm")

#******************************************************************************************************************************

    elif choice == "q":
        #Exit the program
        exit()

    else:
        #User receives another chance to input viable option
        print("Error. Please try again!")

#After choosing an option, the user is returned to the main menu
#Without the following code, the choice would remain "true" and would continue printing infinitely
    print()
    menu()
    choice = (input("Enter your choice, then hit [Enter]"))

#Message that appears when user hits "q" to exit program
print("Thanks for playing!")